Rollback to prettier 2.x since the ESM format of prettier 3.x was breaking us
/home/runner/work/_actions/globalworldwide/dump-context/main/dist/686.index.js:1342
const prettier_require = (0,external_module_.createRequire)(import.meta.url);
                                                                   ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at __nccwpck_require__.f.require (/home/runner/work/_actions/globalworldwide/dump-context/main/dist/index.js:32964:28)
    at /home/runner/work/_actions/globalworldwide/dump-context/main/dist/index.js:32899:40